from setuptools import find_packages, setup

setup(
    name='cmi-bfrb-detection',
    version='0.1.0',
    description='CMI - センサーデータによる行動検出コンペティション',
    author='Kaggle Team',
    license='MIT',
    packages=find_packages('src'),
    package_dir={'': 'src'},
    python_requires='>=3.8',
    install_requires=[
        'pandas>=2.0.0',
        'numpy>=1.24.0',
        'scikit-learn>=1.3.0',
        'matplotlib>=3.7.0',
        'seaborn>=0.12.0',
        'plotly>=5.15.0',
        'xgboost>=1.7.0',
        'lightgbm>=4.0.0',
        'torch>=2.0.0',
        'tsfresh>=0.20.0',
        'tqdm>=4.65.0',
        'joblib>=1.3.0',
        'kaggle>=1.5.0',
    ],
    extras_require={
        'dev': [
            'pytest>=7.4.0',
            'black>=23.0.0',
            'flake8>=6.0.0',
            'isort>=5.12.0',
            'pre-commit>=3.3.0',
            'jupyter>=1.0.0',
            'jupyterlab>=4.0.0',
        ],
        'deep_learning': [
            'pytorch-lightning>=2.0.0',
            'transformers>=4.30.0',
            'wandb>=0.15.0',
        ],
        'visualization': [
            'pandas-profiling>=3.6.0',
            'sweetviz>=2.1.4',
            'plotly-dash>=2.10.0',
            'bokeh>=3.2.0',
        ],
    },
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
)